<a href="https://colab.research.google.com/github/akshata-data/Pandas/blob/main/class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/Salaries.csv")

/tmp/ipykernel_3108/715497070.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/Salaries.csv")

1.  Display Top 10 Rows of The Dataset

In [5]:
df.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011.0,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011.0,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011.0,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011.0,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011.0,NaN,San Francisco,NaN

2. Check Last 10 Rows of The Dataset

In [6]:
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
116465,116466,Christian J Bowman,Police Officer 2,116023.50,8153.55,6204.67,38167.73,130381.72,168549.45,2014.0,NaN,San Francisco,FT
116466,116467,Mary C Godfrey,Police Officer 3,118898.18,8772.66,2038.17,38839.66,129709.01,168548.67,2014.0,NaN,San Francisco,FT
116467,116468,Richard S Burns,Plumber Supervisor 2,120910.08,451.95,6045.40,41132.48,127407.43,168539.91,2014.0,NaN,San Francisco,FT
116468,116469,Edward F Yamada,IS Engineer-Senior,126402.51,0.00,0.00,42134.75,126402.51,168537.26,2014.0,NaN,San Francisco,FT
116469,116470,David A Morales,IS Engineer-Senior,127438.24,0.00,0.00,41090.25,127438.24,168528.49,2014.0,NaN,San Francisco,FT
116470,116471,Enrique O Mixco,Deputy Sheriff,94191.00,20838.73,16240.60,37252.95,131270.33,168523.28,2014.0,NaN,San Francisco,FT
116471,116472,Kelly L Swift,Registered Nurse,114313.80,10970.38,6405.62,36832.68,131689.80,168522.48,2014.0,NaN,San Francisco,PT
116472,116473,Dennis E Cesena,Police Officer 3,118898.10,7079.25,3697.68,38839.63,129675.03,168514.66,2014.0,NaN,San Francisco,FT
116473,116474,Jeffrey H Bishop,Electrician,94355.00,38331.68,0.00,35811.20,132686.68,168497.88,2014.0,NaN,San Francisco,FT
116474,116475,Ramon R Dominguez,Construction Inspector,9.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [7]:
df.shape

(116475, 13)

4.  Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116475 entries, 0 to 116474
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                116475 non-null  int64
 1   EmployeeName      116475 non-null  object
 2   JobTitle          116475 non-null  object
 3   BasePay           115870 non-null  float64
 4   OvertimePay       116474 non-null  float64
 5   OtherPay          116474 non-null  float64
 6   Benefits          80315 non-null   float64
 7   TotalPay          116474 non-null  float64
 8   TotalPayBenefits  116474 non-null  float64
 9   Year              116474 non-null  float64
 10  Notes             0 non-null       float64
 11  Agency            116474 non-null  object
 12  Status            5943 non-null    object
dtypes: float64(8), int64(1), object(4)
memory usage: 11.6+ MB

5. Check Null Values In The Dataset

In [11]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              1
OtherPay                 1
Benefits             36160
TotalPay                 1
TotalPayBenefits         1
Year                     1
Notes               116475
Agency                   1
Status              110532
dtype: int64

6. Drop ID, Notes, Agency, and Status Columns

In [13]:
df.drop(["Id","Notes","Agency","Status"],axis=1,inplace=True)

In [14]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

7. Get Overall Statistics About The Dataframe

In [16]:
df.describe(include="all")

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,116475,116475,115870.000000,116474.000000,116474.000000,80315.000000,116474.000000,116474.000000,116474.000000
unique,104572,2129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,10,4564,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,69709.692915,5551.577023,4049.617309,26589.287929,78949.393149,97284.117293,2012.114472
std,NaN,NaN,44305.455583,12365.980070,8645.359193,15704.970034,52805.115361,65358.257696,0.907919
min,NaN,NaN,-166.010000,-0.010000,-7058.590000,-33.890000,0.000000,-33.890000,2011.000000
25%,NaN,NaN,38133.045000,0.000000,0.000000,14939.040000,40719.860000,47992.925000,2011.000000
50%,NaN,NaN,66622.450000,0.000000,945.565000,29849.660000,73798.050000,93326.035000,2012.000000
75%,NaN,NaN,100733.872500,5165.060000,4831.860000,37163.100000,113848.655000,138322.750000,2013.000000
max,NaN,NaN,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

8. Find Occurrence of The Employee Names  (Top 5)

In [18]:
df['EmployeeName'].value_counts().head(5)

EmployeeName
Kevin Lee      10
Richard Lee     9
KEVIN LEE       9
Stanley Lee     8
MICHAEL LEE     8
Name: count, dtype: int64

9. Find The Number of Unique Job Titles

In [19]:
df['JobTitle'].nunique()

2129

10.Total Number of Job Titles Contain Captain

In [24]:
df['JobTitle'].str.contains("Captain",case=True).sum()

np.int64(406)

11. Display All the Employee Names From Fire Department

In [29]:
df[df['JobTitle'].str.contains("Fire Department",case=False)]["EmployeeName"]

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: object

In [27]:
df['JobTitle']

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
116470                                    Deputy Sheriff
116471                                  Registered Nurse
116472                                  Police Officer 3
116473                                       Electrician
116474                            Construction Inspector
Name: JobTitle, Length: 116475, dtype: object

12. Find Minimum, Maximum, and Average BasePay

In [31]:
print("max value of basepay",df['BasePay'].max())
print("min value of basepay",df['BasePay'].min())
print("average value of basepay",df['BasePay'].mean())

max value of basepay 319275.01
min value of basepay -166.01
average value of basepay 69709.69291507725

13. Replace 'Not Provided' in EmployeeName' Column to NaN

In [56]:
import numpy as np
df["EmployeeName"].replace("NaN",np.nan)

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
116470      Enrique O Mixco
116471        Kelly L Swift
116472      Dennis E Cesena
116473     Jeffrey H Bishop
116474    Ramon R Dominguez
Name: EmployeeName, Length: 116475, dtype: object

14. Drop The Rows Having 5 Missing Values

In [58]:
df[df.isnull().sum(axis=1)==5]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

15. Find Job Title of ALBERT PARDINI

In [40]:
df[df["EmployeeName"].str.contains("Albert Pardini",case=False)]["JobTitle"]

2        CAPTAIN III (POLICE DEPARTMENT)
36519                          Captain 3
Name: JobTitle, dtype: object

16. How Much ALBERT PARDINI Make (Include Benefits)?

In [41]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [47]:
df[df["EmployeeName"].str.contains("Albert Pardini",case=False)]["TotalPayBenefits"]

2        335279.91
36519    253995.29
Name: TotalPayBenefits, dtype: float64

17.Display Name of The Person Having The Highest BasePay

In [ ]:
df

In [70]:
df[df["BasePay"]==df["BasePay"].max()]["EmployeeName"]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
116470      Enrique O Mixco
116471        Kelly L Swift
116472      Dennis E Cesena
116473     Jeffrey H Bishop
116474    Ramon R Dominguez
Name: EmployeeName, Length: 116475, dtype: object

In [76]:
df.loc[df["BasePay"].idxmax(),"EmployeeName"]

'NATHANIEL FORD'

18.Find Average BasePay of All Employee Per Year

In [77]:
df['BasePay'].mean()

np.float64(319275.0099999999)

19. Find Average BasePay of All Employee Per JobTitle
bs

In [80]:
df.groupby("JobTitle")["BasePay"].mean()

JobTitle
ACCOUNT CLERK                                     319275.01
ACCOUNTANT                                        319275.01
ACCOUNTANT INTERN                                 319275.01
ACUPUNCTURIST                                     319275.01
ADMINISTRATIVE ANALYST                            319275.01
                                                    ...
X-RAY LABORATORY AIDE                             319275.01
X-Ray Laboratory Aide                             319275.01
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    319275.01
Youth Comm Advisor                                319275.01
ZOO CURATOR                                       319275.01
Name: BasePay, Length: 2129, dtype: float64

20. Find Average BasePay of Employee Having Job Title ACCOUNTANT

In [81]:
df.groupby("JobTitle")["BasePay"].mean()["ACCOUNTANT"]

np.float64(319275.01)

21. Find Top 5 Most Common Job

In [83]:
df["JobTitle"].value_counts().head(5)

JobTitle
Transit Operator    4564
Registered Nurse    3058
Special Nurse       2915
TRANSIT OPERATOR    2388
Police Officer 3    2171
Name: count, dtype: int64